### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by shoutingpapi** [tangjiapeng/DiffuScene#11]
The 19th line of train_objautoencoder.py
original: 
from utils import yield_forever, load_checkpoints, save_checkpoints
should be:
from training_utils import yield_forever, load_checkpoints, save_checkpoints

**Comment by marfeea** [comment]
> The 19th line of train_objautoencoder.py original: from utils import yield_forever, load_checkpoints, save_checkpoints should be: from training_utils import yield_forever, load_checkpoints, save_checkpoints

Thanks a lot,bro.I'm struggling with this.

**Comment by Aoihigashi** [comment]
> The 19th line of train_objautoencoder.py
> original:
> from utils import yield_forever, load_checkpoints, save_checkpoints
> should be:
> from training_utils import yield_forever, load_checkpoints, save_checkpoints

thanks bro, that helps a lot!!!

**Comment by lipeng-gu** [comment]
Hi, I applied for the 3D-FRONT and 3D-FUTURE dataset on the website (https://tianchi.aliyun.com/dataset/65347), but it has not been approved yet, can you provide a copy of the dataset? It can be done for a fee.

**Comment by shoutingpapi** [comment]
> 3D-FRONT and
Sorry, I can't.
Wait for more days or try apply again may be the best solution, they will reply you at the email that you offered.

**Comment by lipeng-gu** [comment]
> > 3D-FRONT and
> > Sorry, I can't.
> > Wait for more days or try apply again may be the best solution, they will reply you at the email that you offered.

Thank you very much for your reply, I'll wait a few more days.

**Comment by lipeng-gu** [comment]
> > 3D-FRONT and
> > Sorry, I can't.
> > Wait for more days or try apply again may be the best solution, they will reply you at the email that you offered.

Hi, my application has been approved, but the download button won't click at all, have you encountered this problem?

![image](https://github.com/tangjiapeng/DiffuScene/assets/48339331/311659e6-8ac5-4023-9528-b0efe62a817c)

**Comment by shoutingpapi** [comment]
> > > 3D-FRONT and
> > > Sorry, I can't.
> > > Wait for more days or try apply again may be the best solution, they will reply you at the email that you offered.
> 
> Hi, my application has been approved, but the download button won't click at all, have you encountered this problem?
> 
> ![image](https://private-user-images.githubusercontent.com/48339331/294872673-311659e6-8ac5-4023-9528-b0efe62a817c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTA5NjgsIm5iZiI6MTcwNDcxMDY2OCwicGF0aCI6Ii80ODMzOTMzMS8yOTQ4NzI2NzMtMzExNjU5ZTYtOGFjNS00MDIzLTk1MjgtYjBlZmU2MmE4MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwNDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMmNmMjdjYWZmZjMzY2M4MWE3YjYxZWY1ZGZhOWZiMTQwOGM0NzgwYmE1MTQ4NWQ4NGQyZDNkNTA5YzVlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9cdhe6HDutmxPZPul5TXOZlsUirkoVi5YzfWUT2tOQ4)

Change to another browser or check you internet? It's ok for me with microsoft edeg

**Comment by lipeng-gu** [comment]
> > > > 3D-FRONT and
> > > > Sorry, I can't.
> > > > Wait for more days or try apply again may be the best solution, they will reply you at the email that you offered.
> > 
> > 
> > Hi, my application has been approved, but the download button won't click at all, have you encountered this problem?
> > ![image](https://private-user-images.githubusercontent.com/48339331/294872673-311659e6-8ac5-4023-9528-b0efe62a817c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MTA5NjgsIm5iZiI6MTcwNDcxMDY2OCwicGF0aCI6Ii80ODMzOTMzMS8yOTQ4NzI2NzMtMzExNjU5ZTYtOGFjNS00MDIzLTk1MjgtYjBlZmU2MmE4MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwNDQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMmNmMjdjYWZmZjMzY2M4MWE3YjYxZWY1ZGZhOWZiMTQwOGM0NzgwYmE1MTQ4NWQ4NGQyZDNkNTA5YzVlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9cdhe6HDutmxPZPul5TXOZlsUirkoVi5YzfWUT2tOQ4)
> 
> Change to another browser or check you internet? It's ok for me with microsoft edeg

Feeling very frustrated, I still haven't been able to download the dataset up to now. Regarding the issue with dataset download, could you please contact me via email (854215068@qq.com)? I would greatly appreciate it, as I urgently need this dataset at the moment. Thank you very much."
