### ISSUE TITLE
AttributeError: 'ThreedFutureDataset' object has no attribute

### ISSUE THREAD

**Issue by hjjeong** [tangjiapeng/DiffuScene#17]
When I try generate_diffusion.py, it shows 

AttributeError: 'ThreedFutureDataset' object has no attribute 'get_closest_furniture_to_objfeats'

![image](https://github.com/tangjiapeng/DiffuScene/assets/8444098/936495d0-15a6-4ca4-999e-4d2eb011e8c5)

How to solve this problem?

**Comment by hjjeong** [comment]
Have you modified utils.py file in scene_diffusion module?

**Comment by Mr-Faceless** [comment]
I meet the same problem,do you solve the problem?

**Comment by tangjiapeng** [comment]
Hi, I found the simplest way to address this problem is  renaming 'scene_diffusion' as 'scene_synthesis'.

**Comment by hjjeong** [comment]
I have modified the foldername 'scene_diffusion' to 'scene_synthesis', but all dependencies cause error. 
For example, scripts/utils.py file imports functions get_textured_objects from scene_diffusion.utils. 
Should I modify all dependencies and import command?

**Comment by tangjiapeng** [comment]
I push a new commit to address the bug of "No module of scene_synthesis"

**Comment by hjjeong** [comment]
Thanks a lot.
