### ISSUE TITLE
About arrange_scene and complete_scene

### ISSUE THREAD

**Issue by KzZheng** [tangjiapeng/DiffuScene#18]
Hi,

I checked the code and could not find the places to define the arrange_scene and complete_scene functions. Will you plan to release them recently?

**Comment by tangjiapeng** [comment]
Thanks for your update! I added the functions of arrange_scene and completion_scene.

**Comment by scne** [comment]
Probably pretreined model is only for `arrange_scene`. Whene I try the `completion_scene` setup I got:

```
RuntimeError: Error(s) in loading state_dict for DiffusionSceneLayout_DDPM:
	Missing key(s) in state_dict: "fc_partial_condition.0.weight", "fc_partial_condition.2.weight". 
	Unexpected key(s) in state_dict: "fc_arrange_condition.0.weight", "fc_arrange_condition.2.weight".
```
