### ISSUE TITLE
Pretrained Foldingnet Weight

### ISSUE THREAD

**Issue by KzZheng** [tangjiapeng/DiffuScene#19]
Hi,

Currently, the generated models cannot be retrieved by object features since the raw_model_norm_pc_lat32 will be read inside each 3DFuture model folder. Can you share your pretrained foldingnet weight so that I can generate these features? Thanks!

Best,
Kaizhi

**Comment by tangjiapeng** [comment]
I uploaded the pretrained model of Object Shape Autoencoder. You can see my Google Drive folder again.  

https://drive.google.com/file/d/1xuFa_Hh6BOZqfaAnlG-W_9mA1gilU6nI/view?usp=drive_link
