### ISSUE TITLE
How to Evaluation?

### ISSUE THREAD

**Issue by xhanxu** [tangjiapeng/DiffuScene#22]
Hi there, great work! 
What's the exact settings for evaluation? It's 1000 scenes, no floor, no texture?
And, say that it is <no floor, no texture> in evalution, so I should add <--without_floor  --no_texture> when running "preprocess_data.py" to get GT images, right?

**Comment by xhanxu** [comment]
Solved it by further reading the evaluation code. Thanks again for this great work!

**Comment by xhanxu** [comment]
Solved it by further reading the evaluation code. Thanks again for this great work!

**Comment by tangjiapeng** [comment]
yes, we generated 1000 scenes for evaluations. when we render the top2down view images, we didn't add the floor plane. The original CAD texture is disenabled, but the mesh color is decided by the semantic class.

**Comment by xhanxu** [comment]
really appreciate your help! 
just make it clear, I should generate 1000 images (256 x 256) like this:
![rendered_scene_notexture_256](https://github.com/tangjiapeng/DiffuScene/assets/77310777/4882efec-666c-4f43-bd39-2e27a38e4124)

I need make sure the GT images are like this either, but 3D-FRONT has about 3879 GT images, so when I use the **3879 GT images** and **1000 predicted images** to evaluate my trained model, I get fid score: `26.16`, kid score: `0.0086`. 
According to the paper, it should be **`17.21`** and 0.0070 (**`0.70`** x 0.001), which is a little bit better than the model I trained, right? 

Please let me know if there is anything wrong. Thanks!
