### ISSUE TITLE
Model Evaluation and Results

### ISSUE THREAD

**Issue by Rizulv** [tangjiapeng/DiffuScene#28]
Hello , First of all you did great job.
My task was to test your model and see the three cases -
Completition of partial scnes.
Scene Generation.
Text to Scene.
But i have downloaded the pretrained diffuscene and pretrained objautoencoder.
and have also downloaded the pretrained dataset from the link.
But when i tried the two commands generate.sh and the other one  it gave me error that such file doesnt exist.
Can you like guide me and give me the proper steps to do so?
I have edited the paths to the model and dataset in the generate.sh and test files.
Thank you

**Comment by tangjiapeng** [comment]
Hi, can you show the detailed error information so that i can know which files don't exist ?

**Comment by Rizulv** [comment]
Hello its really good to hear from you,
actually i wanted to run your project and just see the three things-
partial scene completition, scene generation and text to scene.
For this i cloned your repo then installed the pretrained models and also
pretuned dataset.
Then after setting the dependencies I had error in installing some of the
modules from environment.yml.
Also to overall run the model you gave generate.sh  and generate_text.sh
files i modified them and then changed the address to model  directory and
dataset.
Can you guide me what wrong step am i taking?
Your help is much appreciated.
Thanking you,
Rizul Vaidya

**Comment by Rizulv** [comment]
also keep getting this error
ModuleNotFoundError: No module named 'open3d'

**Comment by tangjiapeng** [comment]
you can run "pip install open3d"

**Comment by Rizulv** [comment]
can you tell me the steps i need to perform and the files involved for the model evaluation part?
